import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import {useSearchParams } from 'next/navigation'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

export default function Counter() {

    const [number, setNumber] = useState(0);
    const searchParams = useSearchParams();
    const isUser = searchParams.get('username');
    const router = useRouter();
    

    useEffect(() => {
        if(!isUser) {
            router.push(
                '/'
            )
        }
    })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            COUNTER PAGE&nbsp;
            <code className={styles.code}>Hello {isUser} </code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Made By Hudson
            </a>
          </div>
        </div>
        


      
        

        <div className={styles.grid}>
          <h2>
             Days Without Incident:
          </h2>
          <p2>
              {number}
          </p2>
    
          <button class="add" onClick={() => setNumber(number + 1)}>Add</button>
          <button class="reset" onClick={() => setNumber(0)}>Reset</button>
         
        </div>
      </main>
    </>
  )
}
